repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
        files: ^manify/.*\.py$
      # Run the formatter.
      - id: ruff-format
        files: ^manify/.*\.py$

# Pre-commit hooks now configured with ruff for linting and formatting
